package com.model;

import java.util.Date;

/**
 * TCard generated by MyEclipse Persistence Tools
 */

public class TCard implements java.io.Serializable
{

	// Fields

	private Integer cardId;

	private String cardLeixiong;

	private String cardGuize;

	private String cardYouhuizhengce;

	private String cardOne1;

	private String cardOne2;

	private String cardOne3;

	private String cardOne4;

	private Integer cardOne5;

	private Integer cardOne6;

	private Date cardOne7;

	private Date cardOne8;

	// Constructors

	/** default constructor */
	public TCard()
	{
	}

	/** full constructor */
	public TCard(String cardLeixiong, String cardGuize,
			String cardYouhuizhengce, String cardOne1, String cardOne2,
			String cardOne3, String cardOne4, Integer cardOne5,
			Integer cardOne6, Date cardOne7, Date cardOne8)
	{
		this.cardLeixiong = cardLeixiong;
		this.cardGuize = cardGuize;
		this.cardYouhuizhengce = cardYouhuizhengce;
		this.cardOne1 = cardOne1;
		this.cardOne2 = cardOne2;
		this.cardOne3 = cardOne3;
		this.cardOne4 = cardOne4;
		this.cardOne5 = cardOne5;
		this.cardOne6 = cardOne6;
		this.cardOne7 = cardOne7;
		this.cardOne8 = cardOne8;
	}

	// Property accessors

	public Integer getCardId()
	{
		return this.cardId;
	}

	public void setCardId(Integer cardId)
	{
		this.cardId = cardId;
	}

	public String getCardLeixiong()
	{
		return this.cardLeixiong;
	}

	public void setCardLeixiong(String cardLeixiong)
	{
		this.cardLeixiong = cardLeixiong;
	}

	public String getCardGuize()
	{
		return this.cardGuize;
	}

	public void setCardGuize(String cardGuize)
	{
		this.cardGuize = cardGuize;
	}

	public String getCardYouhuizhengce()
	{
		return this.cardYouhuizhengce;
	}

	public void setCardYouhuizhengce(String cardYouhuizhengce)
	{
		this.cardYouhuizhengce = cardYouhuizhengce;
	}

	public String getCardOne1()
	{
		return this.cardOne1;
	}

	public void setCardOne1(String cardOne1)
	{
		this.cardOne1 = cardOne1;
	}

	public String getCardOne2()
	{
		return this.cardOne2;
	}

	public void setCardOne2(String cardOne2)
	{
		this.cardOne2 = cardOne2;
	}

	public String getCardOne3()
	{
		return this.cardOne3;
	}

	public void setCardOne3(String cardOne3)
	{
		this.cardOne3 = cardOne3;
	}

	public String getCardOne4()
	{
		return this.cardOne4;
	}

	public void setCardOne4(String cardOne4)
	{
		this.cardOne4 = cardOne4;
	}

	public Integer getCardOne5()
	{
		return this.cardOne5;
	}

	public void setCardOne5(Integer cardOne5)
	{
		this.cardOne5 = cardOne5;
	}

	public Integer getCardOne6()
	{
		return this.cardOne6;
	}

	public void setCardOne6(Integer cardOne6)
	{
		this.cardOne6 = cardOne6;
	}

	public Date getCardOne7()
	{
		return this.cardOne7;
	}

	public void setCardOne7(Date cardOne7)
	{
		this.cardOne7 = cardOne7;
	}

	public Date getCardOne8()
	{
		return this.cardOne8;
	}

	public void setCardOne8(Date cardOne8)
	{
		this.cardOne8 = cardOne8;
	}

}