package com.model;

import java.util.Date;

/**
 * TQicai generated by MyEclipse Persistence Tools
 */

public class TQicai implements java.io.Serializable
{

	// Fields

	private Integer qicaiId;

	private String qicaiName;

	private String qicaiGoumairiqi;

	private String qicaiBeizhu;

	private String qicaiOne1;

	private String qicaiOne2;

	private String qicaiOne3;

	private String qicaiOne4;

	private Integer qicaiOne5;

	private Integer qicaiOne6;

	private Date qicaiOne7;

	private Date qicaiOne8;

	// Constructors

	/** default constructor */
	public TQicai()
	{
	}

	/** full constructor */
	public TQicai(String qicaiName, String qicaiGoumairiqi, String qicaiBeizhu,
			String qicaiOne1, String qicaiOne2, String qicaiOne3,
			String qicaiOne4, Integer qicaiOne5, Integer qicaiOne6,
			Date qicaiOne7, Date qicaiOne8)
	{
		this.qicaiName = qicaiName;
		this.qicaiGoumairiqi = qicaiGoumairiqi;
		this.qicaiBeizhu = qicaiBeizhu;
		this.qicaiOne1 = qicaiOne1;
		this.qicaiOne2 = qicaiOne2;
		this.qicaiOne3 = qicaiOne3;
		this.qicaiOne4 = qicaiOne4;
		this.qicaiOne5 = qicaiOne5;
		this.qicaiOne6 = qicaiOne6;
		this.qicaiOne7 = qicaiOne7;
		this.qicaiOne8 = qicaiOne8;
	}

	// Property accessors

	public Integer getQicaiId()
	{
		return this.qicaiId;
	}

	public void setQicaiId(Integer qicaiId)
	{
		this.qicaiId = qicaiId;
	}

	public String getQicaiName()
	{
		return this.qicaiName;
	}

	public void setQicaiName(String qicaiName)
	{
		this.qicaiName = qicaiName;
	}

	public String getQicaiGoumairiqi()
	{
		return this.qicaiGoumairiqi;
	}

	public void setQicaiGoumairiqi(String qicaiGoumairiqi)
	{
		this.qicaiGoumairiqi = qicaiGoumairiqi;
	}

	public String getQicaiBeizhu()
	{
		return this.qicaiBeizhu;
	}

	public void setQicaiBeizhu(String qicaiBeizhu)
	{
		this.qicaiBeizhu = qicaiBeizhu;
	}

	public String getQicaiOne1()
	{
		return this.qicaiOne1;
	}

	public void setQicaiOne1(String qicaiOne1)
	{
		this.qicaiOne1 = qicaiOne1;
	}

	public String getQicaiOne2()
	{
		return this.qicaiOne2;
	}

	public void setQicaiOne2(String qicaiOne2)
	{
		this.qicaiOne2 = qicaiOne2;
	}

	public String getQicaiOne3()
	{
		return this.qicaiOne3;
	}

	public void setQicaiOne3(String qicaiOne3)
	{
		this.qicaiOne3 = qicaiOne3;
	}

	public String getQicaiOne4()
	{
		return this.qicaiOne4;
	}

	public void setQicaiOne4(String qicaiOne4)
	{
		this.qicaiOne4 = qicaiOne4;
	}

	public Integer getQicaiOne5()
	{
		return this.qicaiOne5;
	}

	public void setQicaiOne5(Integer qicaiOne5)
	{
		this.qicaiOne5 = qicaiOne5;
	}

	public Integer getQicaiOne6()
	{
		return this.qicaiOne6;
	}

	public void setQicaiOne6(Integer qicaiOne6)
	{
		this.qicaiOne6 = qicaiOne6;
	}

	public Date getQicaiOne7()
	{
		return this.qicaiOne7;
	}

	public void setQicaiOne7(Date qicaiOne7)
	{
		this.qicaiOne7 = qicaiOne7;
	}

	public Date getQicaiOne8()
	{
		return this.qicaiOne8;
	}

	public void setQicaiOne8(Date qicaiOne8)
	{
		this.qicaiOne8 = qicaiOne8;
	}

}