package com.model;

import java.util.Date;

/**
 * TZhijiao generated by MyEclipse Persistence Tools
 */

public class TZhijiao implements java.io.Serializable
{

	// Fields

	private Integer zhijiaoId;

	private Integer zhijiaoJiaolianId;

	private String zhijiaoJiaolianName;

	private String zhijiaoKecheng;

	private String zhijiaoHuiyuan;

	private String zhijiaoOne1;

	private String zhijiaoOne2;

	private String zhijiaoOne3;

	private String zhijiaoOne4;

	private Integer zhijiaoOne5;

	private Integer zhijiaoOne6;

	private Date zhijiaoOne7;

	private Date zhijiaoOne8;

	// Constructors

	/** default constructor */
	public TZhijiao()
	{
	}

	/** full constructor */
	public TZhijiao(Integer zhijiaoJiaolianId, String zhijiaoJiaolianName,
			String zhijiaoKecheng, String zhijiaoHuiyuan, String zhijiaoOne1,
			String zhijiaoOne2, String zhijiaoOne3, String zhijiaoOne4,
			Integer zhijiaoOne5, Integer zhijiaoOne6, Date zhijiaoOne7,
			Date zhijiaoOne8)
	{
		this.zhijiaoJiaolianId = zhijiaoJiaolianId;
		this.zhijiaoJiaolianName = zhijiaoJiaolianName;
		this.zhijiaoKecheng = zhijiaoKecheng;
		this.zhijiaoHuiyuan = zhijiaoHuiyuan;
		this.zhijiaoOne1 = zhijiaoOne1;
		this.zhijiaoOne2 = zhijiaoOne2;
		this.zhijiaoOne3 = zhijiaoOne3;
		this.zhijiaoOne4 = zhijiaoOne4;
		this.zhijiaoOne5 = zhijiaoOne5;
		this.zhijiaoOne6 = zhijiaoOne6;
		this.zhijiaoOne7 = zhijiaoOne7;
		this.zhijiaoOne8 = zhijiaoOne8;
	}

	// Property accessors

	public Integer getZhijiaoId()
	{
		return this.zhijiaoId;
	}

	public void setZhijiaoId(Integer zhijiaoId)
	{
		this.zhijiaoId = zhijiaoId;
	}

	public Integer getZhijiaoJiaolianId()
	{
		return this.zhijiaoJiaolianId;
	}

	public void setZhijiaoJiaolianId(Integer zhijiaoJiaolianId)
	{
		this.zhijiaoJiaolianId = zhijiaoJiaolianId;
	}

	public String getZhijiaoJiaolianName()
	{
		return this.zhijiaoJiaolianName;
	}

	public void setZhijiaoJiaolianName(String zhijiaoJiaolianName)
	{
		this.zhijiaoJiaolianName = zhijiaoJiaolianName;
	}

	public String getZhijiaoKecheng()
	{
		return this.zhijiaoKecheng;
	}

	public void setZhijiaoKecheng(String zhijiaoKecheng)
	{
		this.zhijiaoKecheng = zhijiaoKecheng;
	}

	public String getZhijiaoHuiyuan()
	{
		return this.zhijiaoHuiyuan;
	}

	public void setZhijiaoHuiyuan(String zhijiaoHuiyuan)
	{
		this.zhijiaoHuiyuan = zhijiaoHuiyuan;
	}

	public String getZhijiaoOne1()
	{
		return this.zhijiaoOne1;
	}

	public void setZhijiaoOne1(String zhijiaoOne1)
	{
		this.zhijiaoOne1 = zhijiaoOne1;
	}

	public String getZhijiaoOne2()
	{
		return this.zhijiaoOne2;
	}

	public void setZhijiaoOne2(String zhijiaoOne2)
	{
		this.zhijiaoOne2 = zhijiaoOne2;
	}

	public String getZhijiaoOne3()
	{
		return this.zhijiaoOne3;
	}

	public void setZhijiaoOne3(String zhijiaoOne3)
	{
		this.zhijiaoOne3 = zhijiaoOne3;
	}

	public String getZhijiaoOne4()
	{
		return this.zhijiaoOne4;
	}

	public void setZhijiaoOne4(String zhijiaoOne4)
	{
		this.zhijiaoOne4 = zhijiaoOne4;
	}

	public Integer getZhijiaoOne5()
	{
		return this.zhijiaoOne5;
	}

	public void setZhijiaoOne5(Integer zhijiaoOne5)
	{
		this.zhijiaoOne5 = zhijiaoOne5;
	}

	public Integer getZhijiaoOne6()
	{
		return this.zhijiaoOne6;
	}

	public void setZhijiaoOne6(Integer zhijiaoOne6)
	{
		this.zhijiaoOne6 = zhijiaoOne6;
	}

	public Date getZhijiaoOne7()
	{
		return this.zhijiaoOne7;
	}

	public void setZhijiaoOne7(Date zhijiaoOne7)
	{
		this.zhijiaoOne7 = zhijiaoOne7;
	}

	public Date getZhijiaoOne8()
	{
		return this.zhijiaoOne8;
	}

	public void setZhijiaoOne8(Date zhijiaoOne8)
	{
		this.zhijiaoOne8 = zhijiaoOne8;
	}

}